version: '3.8'

services:
  backend:
    build: ./backend
    image: gitlab-mr-scanner-backend:latest
    environment:
      - GITLAB_API_URL=${GITLAB_API_URL:-https://gitlab.com/api/v4}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - REPOSITORY_URL=${REPOSITORY_URL}
      - PORT=${BACKEND_PORT:-5000}
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"

  frontend:
    image: gitlab-mr-scanner-frontend:latest
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://backend:${BACKEND_PORT:-5000}
    ports:
      - "${FRONTEND_PORT:-9001}:9001"
    depends_on:
      - backend

networks:
  default:
    name: gitlab-mr-scanner-network
