version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GITLAB_API_URL=${GITLAB_API_URL:-https://gitlab.com/api/v4}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - PROJECT_ID=${PROJECT_ID}
      - BACKEND_PORT=${BACKEND_PORT:-5000}
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://backend:${BACKEND_PORT:-5000}
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    name: gitlab-mr-scanner-network
